spring.application.name=simple-jobs-spring-gradle-with-mdc
server.port=9012

job.system.delay=3000
job.manager.delay=15000
job.operator.delay=20000
job.risky.delay=60000
job.slow.delay=60000

api.monitoring.p95-threshold-ms=800
api.monitoring.p99-threshold-ms=1500
api.monitoring.slow-query-threshold-ms=1200

# Elasticsearch
elasticsearch.name=simple-jobs-spring-gradle-with-mdc
elasticsearch.env=local
elasticsearch.url=http://localhost:9200
elasticsearch.username=elastic
elasticsearch.password=Demo3543##

# 배치 설정
elasticsearch.batch.max-size=200
elasticsearch.batch.max-message-size=32768
elasticsearch.connect-timeout-millis=3000
elasticsearch.read-timeout-millis=5000
elasticsearch.max-retries=3
elasticsearch.requeue-on-failure=true
elasticsearch.trust-all-ssl=true
elasticsearch.sleep-time=250
elasticsearch.max-queue-size=104857600
elasticsearch.persistent-writer-thread=false
elasticsearch.include-mdc=true
elasticsearch.include-kvp=true
elasticsearch.operation=index
elasticsearch.errors-to-stderr=true
