spring.application.name=simple-rest-spring-maven
server.port=9201

# H2 In-Memory
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.sql.init.mode=always

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.cube.simple.model

# Elasticsearch
elasticsearch.name=simple-rest-spring-maven
elasticsearch.env=local
elasticsearch.url=http://localhost:9200
elasticsearch.username=elastic
elasticsearch.password=Demo3543##
elasticsearch.batch.max-size=200
elasticsearch.batch.max-message-size=32768
elasticsearch.connect-timeout-millis=3000
elasticsearch.read-timeout-millis=5000
elasticsearch.max-retries=3
elasticsearch.requeue-on-failure=true
elasticsearch.trust-all-ssl=true
elasticsearch.sleep-time=250
elasticsearch.max-queue-size=104857600
elasticsearch.persistent-writer-thread=false
elasticsearch.include-mdc=true
elasticsearch.include-kvp=true
elasticsearch.operation=create
elasticsearch.errors-to-stderr=true
