spring.application.name=simple-jobs-spring-maven-with-java8-lib-bulk
spring.main.web-application-type=none

job.system.delay=3000
job.manager.delay=15000
job.operator.delay=20000
job.risky.delay=60000

# Elasticsearch
elasticsearch.name=simple-jobs-spring-maven-with-java8-lib-bulk
elasticsearch.env=local
elasticsearch.url=http://localhost:9200/_bulk
elasticsearch.username=elastic
elasticsearch.password=Demo3543##
elasticsearch.trust-all-ssl=true
